# ----
# Site

title: Soeasyex DOC
description: Soeasyex Interface documentation.
url: https://xt-com.github.io/xt4-api/
google_analytics_key:
permalink: pretty
baseurl:

# -----
# Build

timezone: Etc/UTC

collections:
  documentation_cn:
    title: 接入说明
    position_number: 1
  order_cn:
    title: api
    position_number: 2

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - CNAME
  - favicon.ico
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - robots.txt


defaults:
  -
    scope:
      path: ""
    values:
      layout: default

  - scope:
      type: "documentation_cn"
    values:
      _hide_content: true

  -
    scope:
      type: "order_cn"
    values:
      _hide_content: true

# -----------
# CloudCannon

types:
  - get
  - put
  - delete
  - post

languages:
  bash: Bash
  c: C
  css: CSS
  html: HTML
  java: Java
  javascript: JavaScript
  json: JSON
  php: PHP
  python: Python
  ruby: Ruby

_options:
  content_markdown:
    format: p h4 h5 h6
    bold: true
    italic: true
    link: true
    bulletedlist: true
    numberedlist: true
    image: true
    table: true
    styles: /css/editor.css
